# PDF Configurations

STRATEGY = 'fast'
MIN_CATEGORIZED_ELEMENT_LENGTH = 5
MIN_UNCATEGORIZED_ELEMENT_LENGTH = 10

# LLM Configurations

MODEL_NAME = 'gpt-3.5-turbo'
MODEL_TEMPERATURE = 0
INPUT_COST = 0.0015 / 1000
OUTPUT_COST = 0.002 / 1000