import os
import dotenv

dotenv.load_dotenv()

DATABASE_URL = os.getenv('DATABASE_URL')

ELASTICSEARCH_USERNAME = os.getenv('ELASTICSEARCH_USERNAME')
ELASTICSEARCH_PASSWORD = os.getenv('ELASTICSEARCH_PASSWORD')

ELASTICSEARCH_HOST = os.getenv('ELASTICSEARCH_HOST')
ELASTICSEARCH_PORT = os.getenv('ELASTICSEARCH_PORT')

INDEX_NAME = os.getenv('INDEX_NAME')
ELASTICSEARCH_SCHEME = os.getenv('ELASTICSEARCH_SCHEME')

SECRET_KEY = os.getenv('SECRET_KEY')
ALGORITHM = os.getenv('ALGORITHM')
ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv('ACCESS_TOKEN_EXPIRE_MINUTES')