import os
import dotenv

dotenv.load_dotenv()

DATABASE_URL = os.getenv('DATABASE_URL')
ELASTICSEARCH_PASSWORD = os.getenv('ELASTICSEARCH_PASSWORD')
ELASTICSEARCH_USERNAME = os.getenv('ELASTICSEARCH_USERNAME')
ELASTICSEARCH_HOST = os.getenv('ELASTICSEARCH_HOST')
ELASTICSEARCH_PORT = os.getenv('ELASTICSEARCH_PORT')
ELASTICSEARCH_SCHEME = os.getenv('ELASTICSEARCH_SCHEME')
INDEX_NAME = os.getenv('INDEX_NAME')