import os
import dotenv

dotenv.load_dotenv()

DATABASE_URL = os.getenv('DATABASE_URL')

ELASTICSEARCH_USERNAME = os.getenv('ELASTICSEARCH_USERNAME')
ELASTICSEARCH_PASSWORD = os.getenv('ELASTICSEARCH_PASSWORD')
ELASTICSEARCH_URL = os.getenv('ELASTICSEARCH_URL')
INDEX_NAME = os.getenv('INDEX_NAME')

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

SECRET_KEY = os.getenv('SECRET_KEY')
ALGORITHM = os.getenv('ALGORITHM')
ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv('ACCESS_TOKEN_EXPIRE_MINUTES')